// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowTests.Features.Authorization
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Попытка войти с неправильным логином либо паролем")]
    public partial class ПопыткаВойтиСНеправильнымЛогиномЛибоПаролемFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "LoginTests.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru"), "Попытка войти с неправильным логином либо паролем", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Негативная проверка входа")]
        [NUnit.Framework.CategoryAttribute("BadLogins")]
        [NUnit.Framework.TestCaseAttribute("РусскийЛогин", "РусскийПароль", null)]
        [NUnit.Framework.TestCaseAttribute("EnglishLogin", "EnglishPassword", null)]
        [NUnit.Framework.TestCaseAttribute("$Пробел", "$Пробел", null)]
        public virtual void НегативнаяПроверкаВхода(string login, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "BadLogins"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Негативная проверка входа", @__tags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
       testRunner.When("открывается страница \"Главная\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 6
    testRunner.Then("пользователь (запоминает значение) \"Не верный логин или пароль!\" \"~Текст ошибки\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 7
       testRunner.And("пользователь (нажимает кнопку) \"Войти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 8
       testRunner.Then("открывается страница \"Авторизация\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Поле",
                        "Значение"});
            table1.AddRow(new string[] {
                        "Логин",
                        string.Format("{0}", login)});
            table1.AddRow(new string[] {
                        "Пароль",
                        string.Format("{0}", password)});
#line 9
       testRunner.And("пользователь (заполняет поле) из таблицы", ((string)(null)), table1, "И ");
#line 13
       testRunner.And("пользователь (нажимает кнопку) \"Войти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 14
       testRunner.Then("пользователь (проверяет значение элемента) \"Текст ошибки\" со значением \"~Текст ош" +
                    "ибки\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
